### ISSUE TITLE
USB camera

### ISSUE THREAD

**Issue by Minion40** [indra4837/yolov4_trt_ros#10]
Hello,

Can you help me to correct this error,
I use a USB camera as input.
roslaunch yolov4_trt_ros video_source.launch input:=v4l2://3
RLException: [video_source.launch] is neither a launch file in package [yolov4_trt_ros] nor is [yolov4_trt_ros] a launch file name
The traceback for the exception was written to the log file

Regards
Minion 40

**Comment by indra4837** [comment]
Hi,

Did you source your workspace, 
```
$ cd ~/catkin_ws
$ source devel/setup.bash
```

**Comment by Minion40** [comment]
cd ~/catkin_ws
procomm@procomm-desktop:~/catkin_ws$ source devel/setup.bash
procomm@procomm-desktop:~/catkin_ws$ cd src/yolov4_trt_ros/launch/
procomm@procomm-desktop:~/catkin_ws/src/yolov4_trt_ros/launch$ roslaunch yolov4_trt_ros video_source.launch input:=v4l2://3
RLException: [video_source.launch] is neither a launch file in package [yolov4_trt_ros] nor is [yolov4_trt_ros] a launch file name
The traceback for the exception was written to the log file

The same error

**Comment by Minion40** [comment]
Hello,

Hello,

I did what you wrote but I got the same message.
can you help me ?

Regrads
Minion40

Le mer. 21 avr. 2021 à 15:29, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
Can i check if you are able to run the other launch files (`yolov4_trt.launch`)? It could be that the `video_source` node is not built properly when you ran `catkin_make`. Maybe you can check that also

**Comment by Minion40** [comment]
Hello,

Can you help me find the problem.
below are the copies of the launch file and the error messages with the
commands used
The source setup bach has been done but nothing has been corrected

vidéo_source.launch
<launch>
<arg name="input" default="v4l2://dev/video3"/>
<arg name="input_width" default="0"/>
<arg name="input_height" default="0"/>
<arg name="input_codec" default="unknown"/>
<arg name="input_loop" default="0"/>

<node pkg="yolov4_trt_ros" type="video_source" name="video_source"
output="screen">
<param name="resource" value="$(arg input)"/>
<param name="width" value="$(arg input_width)"/>
<param name="height" value="$(arg input_height)"/>
<param name="loop" value="$(arg input_loop)"/>
</node>

</launch>

l'erreur
RLException: [video_source.launch] is neither a launch file in package
[yolov4_trt_ros] nor is [yolov4_trt_ros] a launch file name
The traceback for the exception was written to the log file

commande: roslaunch yolov4_trt_ros video_source.launch
input:=v4l2://dev/video3

yolov4_trt.launch
<launch>

<node pkg="yolov4_trt_ros" type="trt_yolo_v4.py" name="yolov4_trt_node"
output="screen">
<param name="video_topic" type="string" value="/video_source/raw" />
<param name="model" type="string" value="yolov4" />
<param name="model_path" type="string" value="$(find yolov4_trt_ros)/yolo/"
/>
<param name="input_shape" type="string" value="416" />
<param name="category_number" type="int" value="80" />
<param name="confidence_threshold" type="double" value="0.5" />
<param name="show_image" type="bool" value="True" />
</node>
</launch>

erreur:
RLException: [yolov4_trt.launch] is neither a launch file in package
[yolov4_trt_ros] nor is [yolov4_trt_ros] a launch file name
The traceback for the exception was written to the log file

commande: roslaunch yolov4_trt_ros yolov4_trt.launch

Thank you
Regards
Minion40

Le mer. 21 avr. 2021 à 18:14, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
i think there is something wrong with your catkin_ws as it does not seem like its building any of the nodes required. Can i check if you have installed all the dependencies required? Also, may I know your environment? 

Hardware: Jetson Nano
Jetpack version: 4.3
ROS version: Melodic

You can also try creating another workspace and building the ROS package again there.

**Comment by Minion40** [comment]
Hello,

Hardware: Jetson TX2
Jetpack version: 4.4
ROS version: Melodic

I added all the bookstores in your tutorial

Le jeu. 22 avr. 2021 à 15:59, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
Hi, could you try shifting the entire `yolov4_trt_ros` into another workspace and follow the steps again to see if its works,

```
# create another workspace
$ mkdir -p yolo_ws/src

# copy the existing package to the new workspace
$ cp -r ~/catkin-ws/src/yolov4_trt_ros/ ~/yolo_ws/src

# build the package using catkin build instead (install the catkin build system first)
$ sudo apt-get install ros-melodic-catkin python-catkin-tools 
$ cd ~/yolo_ws && catkin build
$ source ~/yolo_ws/devel/setup.bash
```

Follow the rest of the instructions in the `README` file and run the launch files again. Let me know if that works!

**Comment by Minion40** [comment]
Hello,

I did as you told me and I still have the same error message
Regards
Minion40

Le jeu. 22 avr. 2021 à 16:17, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
are you able to find the package using roscd?

```
$ roscd yolov4_trt_ros
```

im afraid your catkin_make is not properly building the package. could you post the log for the `catkin_make` or `catkin build`?

**Comment by Minion40** [comment]
Hello,
I tested the command and here is the result which I think is not good
roscd yolov4_trt_ros
roscd: No such package/stack 'yolov4_trt_ros'

As an attachment the request file, hope this is the one you want
Regards
Minion40

Le jeu. 22 avr. 2021 à 17:11, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
im not able to see the attachment. this error is related to your catkin build system as it is not building the package properly. You can try reinstalling ROS melodic again or solve the catkin build system.

**Comment by Minion40** [comment]
Hello,

Here are the unzipped files

Regards
Mr owczarek

Le ven. 23 avr. 2021 à 07:11, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,

I just reinstalled Melodic and it still doesn't work.
I am attaching a file of everything I have installed, maybe I am making a
mistake.
I can't find the solution

Regards
Minion40

**Comment by Minion40** [comment]
Hello,

I just reinstalled Melodic and it still doesn't work.
I am attaching a file of everything I have installed, maybe I am making a
mistake.
I can't find the solution

Regards
Minion40

Le ven. 23 avr. 2021 à 07:11, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
Hi, could you paste the log here or upload it to a Google Drive and send the link here? I cant see the attachment

**Comment by Minion40** [comment]
Hello,

I put the file on the google drive for you, tell me if you can recover them

Minion40

Le ven. 23 avr. 2021 à 16:23, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
Hey, im guessing you are responding to the github email notifications and not on the github issues tab directly. This is probably why Im not able to access any of the links/attachments you are sending. 

Could you respond directly on Github? Thank you.

**Comment by Minion40** [comment]
Hello,


Link used for installation


Installation ROS

http://wiki.ros.org/melodic/Installation/Ubuntu

Commande

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $ (lsb_release
-sc) main"> /etc/apt/sources.list.d/ros-latest.list'



sudo apt-key adv --keyserver 'hkp: //keyserver.ubuntu.com: 80'
--recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654



sudo apt update

sudo apt install ros-melodic-desktop-full

apt search ros-melodic

echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

source ~/.bashrc


sudo apt install python-rosdep python-rosinstall
python-rosinstall-generator python-wstool build-essential



sudo apt install python-rosdep



sudo rosdep init

rosdep update



ROS Melodic

http://wiki.ros.org/catkin#Installing_catkin

selection Melodic

Sudo apt-get install Ros- mélodique -catkin

sudo apt-get install cmake python-catkin-pkg python-empy python-nose
python-setuptools libgtest-dev build-essentia











Creation espace de travail catkin

http://wiki.ros.org/catkin/Tutorials/create_a_workspace

selectionner Melodic

source /opt/ros/noetic/setup.bash

mkdir -p ~/catkin_ws/src

$ cd ~/catkin_ws/

$ catkin_make



Aller file  puis catkin ws clic doit ouvrir « open in terminal »

Taper cd src

Git clone https://github.com/indra4837/yolov4_trt_ros.git



Lien installation programme tracking

https://github.com/indra4837/yolov4_trt_ros

Pycuda



Install pycuda (takes awhile)

$ cd ${HOME}/catkin_ws/src/yolov4_trt_ros/dependencies

$ ./install_pycuda.sh



Si manque commande pip3

https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found



sudo apt-get remove python3-pip; sudo apt-get install python3-pip





Protobuf



Install Protobuf (takes awhile)

$ cd ${HOME}/catkin_ws/src/yolov4_trt_ros/dependencies

$ ./install_protobuf-3.8.0.sh



Onnx



Install onnx (depends on Protobuf above)

$ sudo pip3 install onnx==1.4.1









Numpy 1.15.1



https://linuxconfig.org/install-numpy-on-ubuntu-18-04-bionic-beaver-linux



Installer version python3

sudo apt installer python3-pip

python3 -c "import numpy; print (numpy .__ version__)"

pip3 installer numpy

python3 -c "import numpy; print (numpy .__ version__)"

Vous pouvez simplement placer un fichier vide nommé 'CATKIN_IGNORE' dans
ros_deep_learning. C'est juste un fichier vide qui dit à catkin de ne pas
construire le paquet ros_deep_learning. Voir l'image ci-jointe pour un
exemple.

<https://aws1.discourse-cdn.com/nvidia/original/3X/d/5/d5917c181debf948997b641f225c1cab8e0321ce.png>

*Capture d'écran du 2021-03-26 15-53-101148 × 182 30,6 Ko
<https://aws1.discourse-cdn.com/nvidia/original/3X/d/5/d5917c181debf948997b641f225c1cab8e0321ce.png>*



Installez les dépendances pour vous assurer que le package yolov4_trt_ros
se construit correctement.



Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,


build.symlink.log

Symlinking /home/procomm/yolo_ws/devel/./local_setup.sh
Symlinking /home/procomm/yolo_ws/devel/./local_setup.zsh
Symlinking /home/procomm/yolo_ws/devel/./setup.sh
Symlinking /home/procomm/yolo_ws/devel/./_setup_util.py
Symlinking /home/procomm/yolo_ws/devel/./env.sh
Symlinking /home/procomm/yolo_ws/devel/./setup.bash
Symlinking /home/procomm/yolo_ws/devel/./local_setup.bash
Symlinking /home/procomm/yolo_ws/devel/./cmake.lock
Symlinking /home/procomm/yolo_ws/devel/./setup.zsh
Symlinking
/home/procomm/yolo_ws/devel/lib/pkgconfig/catkin_tools_prebuild.pc
Symlinking
/home/procomm/yolo_ws/devel/share/catkin_tools_prebuild/cmake/catkin_tools_prebuildConfig.cmake
Symlinking
/home/procomm/yolo_ws/devel/share/catkin_tools_prebuild/cmake/catkin_tools_prebuildConfig-version.cmake

Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Helo,

build.symlink.000.log




Symlinking /home/procomm/yolo_ws/devel/./local_setup.sh
Symlinking /home/procomm/yolo_ws/devel/./local_setup.zsh
Symlinking /home/procomm/yolo_ws/devel/./setup.sh
Symlinking /home/procomm/yolo_ws/devel/./_setup_util.py
Symlinking /home/procomm/yolo_ws/devel/./env.sh
Symlinking /home/procomm/yolo_ws/devel/./setup.bash
Symlinking /home/procomm/yolo_ws/devel/./local_setup.bash
Symlinking /home/procomm/yolo_ws/devel/./cmake.lock
Symlinking /home/procomm/yolo_ws/devel/./setup.zsh
Symlinking
/home/procomm/yolo_ws/devel/lib/pkgconfig/catkin_tools_prebuild.pc
Symlinking
/home/procomm/yolo_ws/devel/share/catkin_tools_prebuild/cmake/catkin_tools_prebuildConfig.cmake
Symlinking
/home/procomm/yolo_ws/devel/share/catkin_tools_prebuild/cmake/catkin_tools_prebuildConfig-version.cmake

Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,

build.loadenv.log



Loading environment from: /home/procomm/yolo_ws/devel/env.sh

Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,

build.loadenv.000.log
Loading environment from: /home/procomm/yolo_ws/devel/env.sh



Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,

build.cmake.log

Not searching for unused variables given on the command line.
[36m-- [0m The C compiler identification is GNU 7.5.0
[36m-- [0m The CXX compiler identification is GNU 7.5.0
[36m-- [0m Check for working C compiler: /usr/bin/cc
[36m-- [0m Check for working C compiler: /usr/bin/cc -- works
[36m-- [0m Detecting C compiler ABI info
[36m-- [0m Detecting C compiler ABI info - done
[36m-- [0m Detecting C compile features
[36m-- [0m Detecting C compile features - done
[36m-- [0m Check for working CXX compiler: /usr/bin/c++
[36m-- [0m Check for working CXX compiler: /usr/bin/c++ -- works
[36m-- [0m Detecting CXX compiler ABI info
[36m-- [0m Detecting CXX compiler ABI info - done
[36m-- [0m Detecting CXX compile features
[36m-- [0m Detecting CXX compile features - done
[36m-- [0m Using CATKIN_DEVEL_PREFIX:
/home/procomm/yolo_ws/devel/.private/catkin_tools_prebuild
[36m-- [0m Using CMAKE_PREFIX_PATH: /opt/ros/melodic
[36m-- [0m This workspace overlays: /opt/ros/melodic
[36m-- [0m Found PythonInterp: /usr/bin/python2 (found suitable version
"2.7.17", minimum required is "2")
[36m-- [0m Using PYTHON_EXECUTABLE: /usr/bin/python2
[36m-- [0m Using Debian Python package layout
[36m-- [0m Using empy: /usr/bin/empy
[36m-- [0m Using CATKIN_ENABLE_TESTING: ON
[36m-- [0m Call enable_testing()
[36m-- [0m Using CATKIN_TEST_RESULTS_DIR:
/home/procomm/yolo_ws/build/catkin_tools_prebuild/test_results
[36m-- [0m Found gtest sources under '/usr/src/googletest': gtests will be
built
[36m-- [0m Found gmock sources under '/usr/src/googletest': gmock will be
built
[36m-- [0m Found PythonInterp: /usr/bin/python2 (found version "2.7.17")
[36m-- [0m Looking for pthread.h
[36m-- [0m Looking for pthread.h - found
[36m-- [0m Looking for pthread_create
[36m-- [0m Looking for pthread_create - not found
[36m-- [0m Looking for pthread_create in pthreads
[36m-- [0m Looking for pthread_create in pthreads - not found
[36m-- [0m Looking for pthread_create in pthread
[36m-- [0m Looking for pthread_create in pthread - found
[36m-- [0m Found Threads: TRUE
[36m-- [0m Using Python nosetests: /usr/bin/nosetests-2.7
[36m-- [0m catkin 0.7.29
[36m-- [0m BUILD_SHARED_LIBS is on
[36m-- [0m Configuring done
[36m-- [0m Generating done
[36m-- [0m Build files have been written to:
/home/procomm/yolo_ws/build/catkin_tools_prebuild

Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,

build.cmake.000.log

Not searching for unused variables given on the command line.
[36m-- [0m The C compiler identification is GNU 7.5.0
[36m-- [0m The CXX compiler identification is GNU 7.5.0
[36m-- [0m Check for working C compiler: /usr/bin/cc
[36m-- [0m Check for working C compiler: /usr/bin/cc -- works
[36m-- [0m Detecting C compiler ABI info
[36m-- [0m Detecting C compiler ABI info - done
[36m-- [0m Detecting C compile features
[36m-- [0m Detecting C compile features - done
[36m-- [0m Check for working CXX compiler: /usr/bin/c++
[36m-- [0m Check for working CXX compiler: /usr/bin/c++ -- works
[36m-- [0m Detecting CXX compiler ABI info
[36m-- [0m Detecting CXX compiler ABI info - done
[36m-- [0m Detecting CXX compile features
[36m-- [0m Detecting CXX compile features - done
[36m-- [0m Using CATKIN_DEVEL_PREFIX:
/home/procomm/yolo_ws/devel/.private/catkin_tools_prebuild
[36m-- [0m Using CMAKE_PREFIX_PATH: /opt/ros/melodic
[36m-- [0m This workspace overlays: /opt/ros/melodic
[36m-- [0m Found PythonInterp: /usr/bin/python2 (found suitable version
"2.7.17", minimum required is "2")
[36m-- [0m Using PYTHON_EXECUTABLE: /usr/bin/python2
[36m-- [0m Using Debian Python package layout
[36m-- [0m Using empy: /usr/bin/empy
[36m-- [0m Using CATKIN_ENABLE_TESTING: ON
[36m-- [0m Call enable_testing()
[36m-- [0m Using CATKIN_TEST_RESULTS_DIR:
/home/procomm/yolo_ws/build/catkin_tools_prebuild/test_results
[36m-- [0m Found gtest sources under '/usr/src/googletest': gtests will be
built
[36m-- [0m Found gmock sources under '/usr/src/googletest': gmock will be
built
[36m-- [0m Found PythonInterp: /usr/bin/python2 (found version "2.7.17")
[36m-- [0m Looking for pthread.h
[36m-- [0m Looking for pthread.h - found
[36m-- [0m Looking for pthread_create
[36m-- [0m Looking for pthread_create - not found
[36m-- [0m Looking for pthread_create in pthreads
[36m-- [0m Looking for pthread_create in pthreads - not found
[36m-- [0m Looking for pthread_create in pthread
[36m-- [0m Looking for pthread_create in pthread - found
[36m-- [0m Found Threads: TRUE
[36m-- [0m Using Python nosetests: /usr/bin/nosetests-2.7
[36m-- [0m catkin 0.7.29
[36m-- [0m BUILD_SHARED_LIBS is on
[36m-- [0m Configuring done
[36m-- [0m Generating done
[36m-- [0m Build files have been written to:
/home/procomm/yolo_ws/build/catkin_tools_prebuild

Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by Minion40** [comment]
Hello,

Link used for installation


Installation ROS

http://wiki.ros.org/melodic/Installation/Ubuntu

Commande

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $ (lsb_release
-sc) main"> /etc/apt/sources.list.d/ros-latest.list'



sudo apt-key adv --keyserver 'hkp: //keyserver.ubuntu.com: 80'
--recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654



sudo apt update

sudo apt install ros-melodic-desktop-full

apt search ros-melodic

echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

source ~/.bashrc


sudo apt install python-rosdep python-rosinstall
python-rosinstall-generator python-wstool build-essential



sudo apt install python-rosdep



sudo rosdep init

rosdep update



ROS Melodic

http://wiki.ros.org/catkin#Installing_catkin

selection Melodic

Sudo apt-get install Ros- mélodique -catkin

sudo apt-get install cmake python-catkin-pkg python-empy python-nose
python-setuptools libgtest-dev build-essentia











Creation espace de travail catkin

http://wiki.ros.org/catkin/Tutorials/create_a_workspace

selectionner Melodic

source /opt/ros/noetic/setup.bash

mkdir -p ~/catkin_ws/src

$ cd ~/catkin_ws/

$ catkin_make



Aller file  puis catkin ws clic doit ouvrir « open in terminal »

Taper cd src

Git clone https://github.com/indra4837/yolov4_trt_ros.git



Lien installation programme tracking

https://github.com/indra4837/yolov4_trt_ros

Pycuda



Install pycuda (takes awhile)

$ cd ${HOME}/catkin_ws/src/yolov4_trt_ros/dependencies

$ ./install_pycuda.sh



Si manque commande pip3

https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found



sudo apt-get remove python3-pip; sudo apt-get install python3-pip





Protobuf



Install Protobuf (takes awhile)

$ cd ${HOME}/catkin_ws/src/yolov4_trt_ros/dependencies

$ ./install_protobuf-3.8.0.sh



Onnx



Install onnx (depends on Protobuf above)

$ sudo pip3 install onnx==1.4.1





















Numpy 1.15.1



https://linuxconfig.org/install-numpy-on-ubuntu-18-04-bionic-beaver-linux



Installer version python3

sudo apt installer python3-pip

python3 -c "import numpy; print (numpy .__ version__)"

pip3 installer numpy

python3 -c "import numpy; print (numpy .__ version__)"

Vous pouvez simplement placer un fichier vide nommé 'CATKIN_IGNORE' dans
ros_deep_learning. C'est juste un fichier vide qui dit à catkin de ne pas
construire le paquet ros_deep_learning. Voir l'image ci-jointe pour un
exemple.

<https://aws1.discourse-cdn.com/nvidia/original/3X/d/5/d5917c181debf948997b641f225c1cab8e0321ce.png>

*Capture d'écran du 2021-03-26 15-53-101148 × 182 30,6 Ko
<https://aws1.discourse-cdn.com/nvidia/original/3X/d/5/d5917c181debf948997b641f225c1cab8e0321ce.png>*



Installez les dépendances pour vous assurer que le package yolov4_trt_ros
se construit correctement.



Le ven. 23 avr. 2021 à 16:47, Indra Kurniawan ***@***.***> a
écrit :

**Comment by indra4837** [comment]
it looks like your ros installation is okay and you are not missing any important steps. Can i confirm that running other nodes (such as the ones in ROS tutorial page) works for you? I suspect this might be a ROS issue and not this package.

**Comment by indra4837** [comment]
Closing this issue, feel free to reopen it if you have any more problems!
