### ISSUE TITLE
Something about the  yolov4 can't work with a mp4 file or USB cam

### ISSUE THREAD

**Issue by Heodel** [indra4837/yolov4_trt_ros#11]
Hello,
Thank you for your looking my question in your busy schedule!

**Platform:  Jetson Nano
                      Ros-melodic
                      Ubuntu 18.04 based on arm
                      cv_bridge based on python3.6**

I got a **yolov4-416.trt** Model using the **./download_yolo.sh and convert_yolo_trt.sh** 

Then I test the program with the command:

1.  roslaunch yolov4_trt_ros video_source.launch input:=/home/nvidia/oversize.mp4
2.  roslaunch yolov4_trt_ros yolov4_trt.launch

But with the process on, there is no output label or boxes results in the detection window **YOLOv4 DETECTION RESULTS**
you can see the image results as follow:
![Screenshot from 2021-04-24 02-22-25](https://user-images.githubusercontent.com/34372187/115916311-3aec7200-a4a7-11eb-980c-37dfb5b3c740.png)

I am looking forward to your reply as soon as possible,thank you very much!

**Comment by Heodel** [comment]
**rostopic echo /detections**
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
header: 
  seq: 1
  stamp: 
    secs: 1619204669
    nsecs: 480823278
  frame_id: "camera"
detections: []
---
header: 
  seq: 2
  stamp: 
    secs: 1619204679
    nsecs: 519422054
  frame_id: "camera"
detections: []
---
header: 
  seq: 3
  stamp: 
    secs: 1619204680
    nsecs: 589275598
  frame_id: "camera"
detections: []
---
header: 
  seq: 4
  stamp: 
    secs: 1619204680
    nsecs: 994405269
  frame_id: "camera"
detections: []
---
header: 
  seq: 5
  stamp: 
    secs: 1619204681
    nsecs: 325216770
  frame_id: "camera"
detections: []
---
header: 
  seq: 6
  stamp: 
    secs: 1619204681
    nsecs: 653379917
  frame_id: "camera"
detections: []
---
header: 
  seq: 7
  stamp: 
    secs: 1619204681
    nsecs: 985752820
  frame_id: "camera"
detections: []
---
header: 
  seq: 8
  stamp: 
    secs: 1619204682
    nsecs: 439900159
  frame_id: "camera"
detections: []
---
header: 
  seq: 9
  stamp: 
    secs: 1619204682
    nsecs: 786917686
  frame_id: "camera"
detections: []
---
header: 
  seq: 10
  stamp: 
    secs: 1619204683
    nsecs: 117529630
  frame_id: "camera"
detections: []
---
header: 
  seq: 11
  stamp: 
    secs: 1619204683
    nsecs: 474802017
  frame_id: "camera"
detections: []
---
header: 
  seq: 12
  stamp: 
    secs: 1619204683
    nsecs: 821820259
  frame_id: "camera"
detections: []
---
header: 
  seq: 13
  stamp: 
    secs: 1619204684
    nsecs: 149898052
  frame_id: "camera"
detections: []
---
header: 
  seq: 14
  stamp: 
    secs: 1619204684
    nsecs: 470993041
  frame_id: "camera"
detections: []
---
header: 
  seq: 15
  stamp: 
    secs: 1619204684
    nsecs: 797467947
  frame_id: "camera"
detections: []
---
header: 
  seq: 16
  stamp: 
    secs: 1619204685
    nsecs: 133927345
  frame_id: "camera"
detections: []
---
header: 
  seq: 17
  stamp: 
    secs: 1619204685
    nsecs: 513645410
  frame_id: "camera"
detections: []
---
header: 
  seq: 18
  stamp: 
    secs: 1619204685
    nsecs: 842870473
  frame_id: "camera"
detections: []
---
header: 
  seq: 19
  stamp: 
    secs: 1619204686
    nsecs: 183943748
  frame_id: "camera"
detections: []
---
header: 
  seq: 20
  stamp: 
    secs: 1619204686
    nsecs: 524326086
  frame_id: "camera"
detections: []
---
header: 
  seq: 21
  stamp: 
    secs: 1619204686
    nsecs: 866849422
  frame_id: "camera"
detections: []
---
header: 
  seq: 22
  stamp: 
    secs: 1619204687
    nsecs: 197349309
  frame_id: "camera"
detections: []
---
header: 
  seq: 23
  stamp: 
    secs: 1619204687
    nsecs: 536478757
  frame_id: "camera"
detections: []
---
header: 
  seq: 24
  stamp: 
    secs: 1619204687
    nsecs: 866652250
  frame_id: "camera"
detections: []
---
header: 
  seq: 25
  stamp: 
    secs: 1619204688
    nsecs: 192340850
  frame_id: "camera"
detections: []
---
header: 
  seq: 26
  stamp: 
    secs: 1619204688
    nsecs: 516493082
  frame_id: "camera"
detections: []
---
header: 
  seq: 27
  stamp: 
    secs: 1619204688
    nsecs: 834228515
  frame_id: "camera"
detections: []
---
header: 
  seq: 28
  stamp: 
    secs: 1619204689
    nsecs: 161202430
  frame_id: "camera"
detections: []
---
header: 
  seq: 29
  stamp: 
    secs: 1619204689
    nsecs: 497174501
  frame_id: "camera"
detections: []
---
header: 
  seq: 30
  stamp: 
    secs: 1619204689
    nsecs: 840080022
  frame_id: "camera"
detections: []
---
header: 
  seq: 31
  stamp: 
    secs: 1619204690
    nsecs: 195339918
  frame_id: "camera"
detections: []
---
header: 
  seq: 32
  stamp: 
    secs: 1619204690
    nsecs: 546848535
  frame_id: "camera"
detections: []
---
header: 
  seq: 33
  stamp: 
    secs: 1619204690
    nsecs: 884192705
  frame_id: "camera"
detections: []
---
header: 
  seq: 34
  stamp: 
    secs: 1619204691
    nsecs: 146670818
  frame_id: "camera"
detections: []
---
header: 
  seq: 35
  stamp: 
    secs: 1619204691
    nsecs: 429933309
  frame_id: "camera"
detections: []
---
header: 
  seq: 36
  stamp: 
    secs: 1619204691
    nsecs: 682560205
  frame_id: "camera"
detections: []
---

**Comment by indra4837** [comment]
can i confirm that the node is running? it looks like either the node is not running or the camera feed topic is not correct. 

maybe you can do a `rosnode info /yolov4_trt_node` and paste the output here?

**Comment by Heodel** [comment]
Thank you very much for your message.
This is the Debug information for  which the command as follow:
_**rosnode info /yolov4_trt_node**_

--------------------------------------------------------------------------------
Node [/yolov4_trt_node]
Publications: 
 * /detections [yolov4_trt_ros/Detector2DArray]
 * /result/overlay [sensor_msgs/Image]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /video_source/raw [sensor_msgs/Image]

Services: 
 * /yolov4_trt_node/get_loggers
 * /yolov4_trt_node/set_logger_level


contacting node http://nvidia-208:41887/ ...
Pid: 12668
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound (38449 - 127.0.0.1:58382) [60]
    * transport: TCPROS
 * topic: /video_source/raw
    * to: /video_source (http://nvidia-208:43623/)
    * direction: inbound
    * transport: TCPROS

**Comment by indra4837** [comment]
The rosnode info looks good to me. It is subscribing to the correct topic and publishing to the right topics. 

Could you maybe paste the log for when you run `roslaunch yolov4_trt_ros yolov4_trt.launch`? I suspect that the node is launching properly and there might be errors there.

**Comment by indra4837** [comment]
Closing this issue. Feel free to reopen it if you have any more problems!

**Comment by Luna2199** [comment]
I have the  same error.
I get correct result in Jetson NX, but I copied and do same things in Jetson Nano, it doesn't work.
I can't got any thing as well.

**Comment by s-sarahSM** [comment]
@Heodel Can you tell me please if you find a solution to your problème because i have the same error.
Thank you for advance
