### ISSUE TITLE
Issue with yolo_layer.cu

### ISSUE THREAD

**Issue by fmartinmonier** [indra4837/yolov4_trt_ros#13]
Hi! 

First of all, thanks a lot for your hard work on this great package!

I get an error when launching the launch file yolov3_trt.launch:
`python3: yolo_layer.cu:71: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(const void*, size_t): Assertion d == a + length' failed.`

This is quite strange as I can see yolo_layer.cu comes from JK Jung's package and I was able to run his package with the same setup:

- Ubuntu 18.04
- ROS Melodic
- TensorRT 7.1.3.0
- Cuda 10.2
- OpenCV 4.2.0
- Pycuda 2019.1.2

Any idea what could be the cause of this issue?

Thanks a lot!

**Comment by fmartinmonier** [comment]
Found the answer myself in the end.

The TensorRT weight file I was using was generated by a different repo. Re-generating one with this repo solved the issue.

**Comment by indra4837** [comment]
Closing this issue, feel free to reopen it
