### ISSUE TITLE
Strange bounding boxes when batch processing

### ISSUE THREAD

**Issue by fmartinmonier** [indra4837/yolov4_trt_ros#14]
Hi!

I'm currently working on an object detection pipeline using yolov3. As the pipeline takes inputs from several cameras, I was thinking of using your trt_yolo_v4_batch.py script.

I tried it out with a yolov3-416 object detector and everything worked great. However, with yolov3-tiny-416, I am getting a weird behaviour. It seems like bounding boxes of a certain image are displayed on several image streams simultaneously. 

For example, in the following gif, you can see that a bounding box is correctly displayed on the /detection_image/right image stream but the same bounding box is also displayed on the /detection_image/front image stream. I added a frame where this issue occurs. 

Do you know what could be the issue here ?

![gif](https://github.com/fmartinmonier/test/blob/master/vlc-record-2021-06-15-16h28m06s-screencast-2021-06-15-14-49-53mp4_jvegGecL.gif)

![frame of interest](https://github.com/fmartinmonier/test/blob/master/Screenshot%20from%202021-06-15%2016-30-17.png)

Thanks a lot for your time!

**Comment by indra4837** [comment]
Apologies for my super late reply. I hope you've figured the problem out. 

If not, I'm guessing the detection outputs are not wired up properly (input to output pairs) or yolov4-tiny-416 has a pretty poor detection accuracy. Judging by your video and the environment, there might be false detection from the model. Perhaps you can try fine-tuning the tiny-yolo model to increase accuracy (while still maintaining detection speed). 

P.s I love your work on using the model (and a robot) to detect survivors!

**Comment by fmartinmonier** [comment]
Thanks for your answer and your support! I'm glad I could use your repo for this application!

I never really found the solution but I guess the same as you: my model had a pretty low detection accuracy. Maybe some mysterious things happening during conversion to a TRT model.

**Comment by indra4837** [comment]
Yeah, conversion to TRT model usually rounds off the weights and makes it less accurate (marginally). All the best and thank you for using this repo!
