### ISSUE TITLE
Ros melodic and python3 compatibility issues

### ISSUE THREAD

**Issue by Aloukik21** [indra4837/yolov4_trt_ros#16]
How to run python3 files with ros melodic as Ros melodic is purely based on python2.7.

**Comment by indra4837** [comment]
Hi, you are right. ROS melodic only officially supports Python 2.7. However, you can use python3 on ros melodic by just running `python3 ros_script.py` or using a virual env. There are a few threads on ROS answers forum on this, do check them out!

**Comment by indra4837** [comment]
Closing this issue, feel free to reopen it if you run into other problems!

**Comment by s-sarahSM** [comment]
@Aloukik21 Can you please tell me how did you solve your problem

**Comment by havvanurbozomeroglu** [comment]
@s-sarahSM  and  @Aloukik21 i have same issue.  Can you tell me how did you solve your problem? Please.
