### ISSUE TITLE
Is it possible for install TensorRT package with no Jetson environment?

### ISSUE THREAD

**Issue by suesuekkim** [indra4837/yolov4_trt_ros#17]
![image](https://user-images.githubusercontent.com/78398919/132116437-ad8552f1-6e1c-45ff-9a54-40fcad774a1b.png)

My current environment doesn't have Jetson Xavier AGX.
Is it possible to install this TensorRT package?

**Comment by indra4837** [comment]
Hi, apologies for the late reply. Yes, you can still use this package. However, you still need to install TensorRT. Follow this [link](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing) for instructions on how to install
