### ISSUE TITLE
compatibility with tensor rt8

### ISSUE THREAD

**Issue by tlgkyn06** [indra4837/yolov4_trt_ros#18]
thanks for such a efficient work but when I run on my system ;
Nvidia Xavier AGX
Jetpack 4.6
Cuda 10.2
Tensor rt8

It throws out error as below
![image](https://user-images.githubusercontent.com/45598280/132202605-b0d25c73-b493-4628-8944-b714d55f51d1.png)

Any idea to fix it?

**Comment by derektan95** [comment]
Hi @tlgkyn06, 

May I know how you ended up solving this issue? Thanks.

**Comment by tlgkyn06** [comment]
@derektan95  converting codes scripts are old for trt8 use newer scripts like : https://github.com/jkjung-avt/tensorrt_demos/tree/master/yolo
