### ISSUE TITLE
For help on ros message

### ISSUE THREAD

**Issue by Shame-fight** [indra4837/yolov4_trt_ros#2]
I am using your code on the robot and it is currently running normally. I have two questions that need your help:
1. 1. The ros message needs to be sent when the target is detected, instead of sending it all the time.
My goal is only one class of 'person'. Only when a person is detected, I need to send a message. I only need to publish a simple message like 'stop' to another node to receive it to control the robot's walking. How should I modify Code.
2. I run on jetson nano, so I tend to use yolov3-ting or yolov4-tiny. Can you add these two models?
Thank you for any help and look forward to receiving your reply. Thank you.
@indra4837

**Comment by indra4837** [comment]
> 1. 1. The ros message needs to be sent when the target is detected, instead of sending it all the time.
>       My goal is only one class of 'person'. Only when a person is detected, I need to send a message. I only need to publish a simple message like 'stop' to another node to receive it to control the robot's walking. How should I modify Code.

You can simply place a wrapper function after running the `detect` function and only publishing a message if the boxes is not empty. If you need to only publish once, you can store the state and publish messages accordingly. 

> 2. I run on jetson nano, so I tend to use yolov3-ting or yolov4-tiny. Can you add these two models?

You can rename the model parameter as yolov4-tiny and place the .trt file into the yolo folder. I have tested the code with yolov4-tiny and have successfully used it.

**Comment by Shame-fight** [comment]
Thanks for your reply, I have solved this problem. In addition, does your code use python2 or python3? Because I found that install_pycuda.sh is based on python3. But I encountered some problems when using it, and installed pycuda using pip (Based on py2).
@indra4837

**Comment by indra4837** [comment]
Yupp, install_pycuda.sh installation script is based on python3. 

By default, ROS Melodic uses python2 and thus, pycuda should be installed using pip. Thanks for pointing that out.

I have not tried using python3 for ROS Melodic but it is possible to do so (there are resources online for this). I believe future ROS distro (ROS Noetic onwards) is using python3.

**Comment by Shame-fight** [comment]
You are welcome.. I have a question: Is opencv not needed? Cmakelists.txt in the code needs to specify opencv, but it is not linked to any opencv library. I only found that the display image part of the trt_yolo_v3.py file requires opencv. This Does it mean that I only need to install python-opencv. If you don't need to display images, opencv does not need to be installed. Is my understanding correct?

**Comment by indra4837** [comment]
We still need OpenCV for the cv_bridge function. This is because the code processes images in OpenCV format but the input is ROS Image format. Thus, cv_bridge is required to do the necessary conversion here

**Comment by Shame-fight** [comment]
Fine,Thank you for your reply.
