### ISSUE TITLE
can this repo used in pc x86 platform?

### ISSUE THREAD

**Issue by yantaixu0120** [indra4837/yolov4_trt_ros#3]
hello, can this repo used in pc x86 platform?

**Comment by indra4837** [comment]
Yes you can use it on x86 platform. You need to download and install TensorRT 7+ on your pc. 

You can only use the inference node and not the video capture node as it is written with the jetson device in mind.

Also, remove the lines that indicate jetson in the CMakelists.txt and the video_capture node accordingly. 

Let me know if you need any help, thanks!

**Comment by yantaixu0120** [comment]
> Yes you can use it on x86 platform. You need to download and install TensorRT 7+ on your pc.
> 
> You can only use the inference node and not the video capture node as it is written with the jetson device in mind.
> 
> Also, remove the lines that indicate jetson in the CMakelists.txt and the video_capture node accordingly.
> 
> Let me know if you need any help, thanks!

thanks very much!!!,I have placed a CATKIN_IGNORE in the ros_deep_learning package,but i get the follow errros  when i run the catkin_make -j12 command:

"CMake Error at yolov4_trt_ros/CMakeLists.txt:42 (add_executable):
  add_executable cannot create target "video_source" because another target
  with the same name already exists."

Should I write someting in the  CATKIN_IGNORE file in the ros_deep_learning?

**Comment by indra4837** [comment]
you can remove the executable line (line 42) in the CMakeLists.txt as that executable requires a jetson device. Let me know if that works!

**Comment by yantaixu0120** [comment]
> you can remove the executable line (line 42) in the CMakeLists.txt as that executable requires a jetson device. Let me know if that works!

Hello,This approach is works,thanks very much!
but there seem to be tow mistakes in the  yolo_to_onnx.py file,there have no the verify_classes() function and get_input_wh() function in the line 879 and 884  Respectively...

**Comment by yantaixu0120** [comment]
> > you can remove the executable line (line 42) in the CMakeLists.txt as that executable requires a jetson device. Let me know if that works!
> 
> Hello,This approach is works,thanks very much!
> but there seem to be tow mistakes in the yolo_to_onnx.py file,there have no the verify_classes() function and get_input_wh() function in the line 879 and 884 Respectively...

O,I have found the two functions ,thanks!!!
