### ISSUE TITLE
having a problem while running the node

### ISSUE THREAD

**Issue by Hagaik92** [indra4837/yolov4_trt_ros#4]
Hello, 
Im having the following problem while running the node:
![Screenshot from 2021-01-28 21-24-04](https://user-images.githubusercontent.com/71939673/106188260-69f88d80-61af-11eb-96d5-549e4fb60ef6.png)

Im using Jetson Xavier and trying to run yolov4 with video from my ZED2 camera.
the error is
ImportError: /home/greensail/cv_ws/devel/lib/python2.7/dist-packages/cv_bridge/boost/cv_bridge_boost.so: undefined symbol: _ZTIN5boost6python7objects21py_function_impl_baseE

**Comment by indra4837** [comment]
@Hagaik92 

it looks like there might be something wrong with your cv_birdge. Could you try rebuilding cv_bridge? 

**Note**: cv_bridge requires OpenCV3 to run.

**Comment by Hagaik92** [comment]
i have tried to rebuild cv_bridge ,nothing has changed, im using OpenCv 3.4.0

**Comment by indra4837** [comment]
Im not sure why you're having the errors. I'm currently using OpenCv 3.4 as well on the Xavier. Perhaps reinstall the OpenCV 3.4 from this [link](https://github.com/jetsonhacks/buildOpenCVXavier)

**Comment by indra4837** [comment]
I'll close this issue, feel free to reopen it if its not solved
