### ISSUE TITLE
small question

### ISSUE THREAD

**Issue by Minion40** [indra4837/yolov4_trt_ros#9]
Hello,

I put th commande 
 ./convert_yolo_trt.sh 
YOLOv3 or YOLOv4. Input 3 or 4
4
Do you want to download the model? [Y/N]
y
What is the input shape? Input 288 or 416 or 608
416
Creating yolov4-416.cfg and yolov4-416.weights
How many categories are there?
An d i have this question What should be done ?
thank you for your help
Regards
Minion40

**Comment by indra4837** [comment]
The number of categories should be the number of classes you have trained the model on. If you used the `./download_yolo.sh`, then it will be downloading the yolo weights trained on MS COCO. 

Thus, there will be 80 categories inside. I'll remove that prompt since it'll almost always be 80
